ktor:
  application:
    modules:
      - dev.psegerfast.warehouse.framework.ktor.ApplicationKt.module

  deployment:
    port: 8080

  database:
    driver: "org.h2.Driver"
    url: "jdbc:h2:./src/main/resources/warehouse_db"
    # These har here for demonstration purposes only. In production these should be
    # stored as environment variables or in a separate file outside of version control.
    user: "admin"
    password: "abc"
